export const GET_PRICE_DATA_REQUEST = 'GET_PRICE_DATA_REQUEST'
export const GET_PRICE_DATA_SUCCES = 'GET_PRICE_DATA_SUCCESS'
export const GET_PRICE_DATA_ERROR = 'GET_PRICE_DATA_ERROR'

export const GET_PORTFOLIO_REQUEST = 'GET_PORTFOLIO_REQUEST'
export const GET_PORTFOLIO_SUCCESS = 'GET_PORTFOLIO_SUCCESS'
export const GET_PORTFOLIO_ERROR = 'GET_PORTFOLIO_ERROR'

export const GET_CRYPTO_LISTINGS_REQUEST = 'GET_CRYPTO-LISTINGS_REQUEST'
export const GET_CRYPTO_LISTINGS_SUCCESS = 'GET_CRYPTO_LISTINGS_SUCCESS'
export const GET_CRYPTO_LISTINGS_ERROR = 'GET_CRYPTO_LISTINGS_ERROR'

export const EDIT_PORTFOLIO_REQUEST = 'EDIT_PORTFOLIO_REQUEST'
export const EDIT_PORTFOLIO_SUCCESS = 'EDIT_PORTFOLIO_SUCCESS'
export const EDIT_PORTFOLIO_ERROR = 'EDIT_PORTFOLIO_ERROR'

export const FORMAT_PORTFOLIO = 'FORMAT_PORTFOLIO'
export const EDIT_PORTFOLIO_TOGGLE = 'EDIT PORTFOLIO_TOGGLE'