export const GET_PRICE_DATA_REQUEST = 'GET_PRICE_DATA_REQUEST'
export const GET_PRICE_DATA_SUCCES = 'GET_PRICE_DATA_SUCCESS'
export const GET_PRICE_DATA_ERROR = 'GET_PRICE_DATA_ERROR'

export const FORMAT_PORTFOLIO = 'FORMAT_PORTFOLIO'